@WebApi_HostAddress = http://localhost:5001

POST {{WebApi_HostAddress}}/api/claims
Content-Type: application/json
Accept: application/json,
{
  "statusId": 3,
  "typeId": 3,
  "assignedAdjusterId": null
}
###

GET {{WebApi_HostAddress}}/api/claims
Accept: appication/json
###

GET {{WebApi_HostAddress}}/api/claims/2
Accept: appication/json
###